# Generated by Django 5.0.2 on 2024-03-04 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='enableSignUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signUpEnabled', models.BooleanField(default=False, verbose_name='Enable Sign Ups?')),
            ],
        ),
    ]
