# Generated by Django 5.0.2 on 2024-03-04 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0002_enablesignup'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together=set(),
        ),
    ]
