# Generated by Django 5.0.2 on 2024-03-08 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0003_alter_attendance_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendee',
            name='type',
            field=models.CharField(choices=[('crew', 'Crew'), ('staff', 'Staff'), ('intercessor', 'Intercessor'), ('guest', 'Guest')], default='crew', max_length=30, verbose_name='Person Type'),
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('attendee', 'meal')},
        ),
    ]
