# Generated by Django 5.0.2 on 2024-03-09 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0005_remove_attendee_type_attendee_half_plates'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendee',
            name='person_type',
            field=models.CharField(choices=[('crew', 'Crew'), ('staff', 'Staff'), ('intercessor', 'Intercessor'), ('guest', 'Guest')], default='crew', max_length=30, verbose_name='Person Type'),
        ),
    ]
