# Generated by Django 5.0.2 on 2024-03-09 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0006_attendee_person_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendee',
            name='vegan',
        ),
    ]
