# Generated by Django 5.0.2 on 2024-03-10 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0008_alter_attendee_half_plates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='latitude',
            field=models.DecimalField(decimal_places=4, max_digits=40, verbose_name='Set Latitude'),
        ),
        migrations.AlterField(
            model_name='meal',
            name='longitude',
            field=models.DecimalField(decimal_places=4, max_digits=40, verbose_name='Set Longitude'),
        ),
    ]
