# Generated by Django 5.0.2 on 2024-03-14 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0010_alter_meal_latitude_alter_meal_longitude'),
    ]

    operations = [
        migrations.CreateModel(
            name='announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40, verbose_name='Announcement Title')),
                ('description', models.TextField(blank=True, verbose_name='Announcement Description')),
            ],
        ),
    ]
