# Generated by Django 5.0.2 on 2024-04-18 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0012_attendee_notes_attendee_vegan_attendee_vegetarian'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendee',
            name='nut_allergy',
            field=models.BooleanField(default=False, verbose_name='Nut Allergy'),
        ),
    ]
